export const AUTH_LOADER_START = 'AUTH_LOADER_START';
export const AUTH_LOADER_STOP = 'AUTH_LOADER_STOP';

export const AUTH_ERROR = 'AUTH_ERROR';

export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_CREDENTIALS_SUCCESS = 'AUTH_CREDENTIALS_SUCCESS';
export const AUTH_CREDENTIALS_FAIL = 'AUTH_CREDENTIALS_FAIL';

export const AUTH_VERIFY_SUCCESS = 'AUTH_VERIFY_SUCCESS';
