export const STORE_LOADER_START = 'STORE_LOADER_START';
export const STORE_LOADER_STOP = 'STORE_LOADER_STOP';

export const STORE_ERROR = 'STORE_ERROR';

export const STORE_FAIL = 'STORE_FAIL';

export const AUTH_CHECK_STATE_SUCCESS = 'AUTH_CHECK_STATE_SUCCESS';

export const ADD_STORE_SUCCESS = 'ADD_STORE_SUCCESS';
export const GET_ALL_STORES_SUCCESS = 'GET_ALL_STORES_SUCCESS';