import Login from "../containers/Auth/Login/Login";
import AddStore from "../containers/Store/Add/AddStore";
import StoreListing from "../containers/Store/Listing/StoreListing";
import Store from "../containers/Store/Store/Store";
import localStrings from "../localisation/localisedStringMapper";

const ROUTES = [
  {
    path: "/login",
    key: localStrings.LOGIN_ROUTE_HEADER,
    exact: true,
    is_protected: false,
    component: Login,
    show_header: false,
    is_default: true,
  },
  {
    path: "/dashboard",
    key: localStrings.DASHBOARD_ROUTE_HEADER,
    exact: false,
    is_protected: true,
    component: () => <p>this is dashboard</p>,
    show_header: true,
    is_default: false,
    is_sidebar: true,
    icon: "fas fa-columns",
  },
  {
    path: "/shipments",
    key: localStrings.SHIPMENTS_ROUTE_HEADER,
    exact: false,
    is_protected: true,
    component: () => <p>this is shipments</p>,
    show_header: true,
    is_default: false,
    is_sidebar: true,
    icon: "far fa-save",
  },
  {
    path: "/products",
    key: localStrings.PRODUCTS_ROUTE_HEADER,
    exact: false,
    is_protected: true,
    component: () => <p>this is products</p>,
    show_header: true,
    is_default: false,
    is_sidebar: true,
    icon: "fas fa-box-open",
  },
  {
    path: "/stores",
    key: localStrings.STORES_ROUTE_HEADER,
    exact: false,
    is_protected: true,
    component: StoreListing,
    show_header: true,
    is_default: true,
    is_sidebar: true,
    icon: "fas fa-store",
    routes: [
      {
        path: "/add",
        key: localStrings.ADD_STORE_ROUTE_HEADER,
        exact: true,
        is_protected: true,
        component: AddStore,
        show_header: false,
        is_default: false,
        is_modal: true,
      },
    ],
  },
  {
    path: "/store/:id",
    key: localStrings.STORE_ROUTE_HEADER,
    exact: true,
    is_protected: true,
    component: Store,
    show_header: true,
  },
  {
    path: "/reports",
    key: localStrings.REPORTS_ROUTE_HEADER,
    exact: false,
    is_protected: true,
    component: () => <p>this is reports</p>,
    show_header: true,
    is_default: false,
    is_sidebar: true,
    icon: "fas fa-file-alt icon",
  },
  {
    path: "/suppliers",
    key: localStrings.SUPPLIERS_ROUTE_HEADER,
    exact: false,
    is_protected: true,
    component: () => <p>this is suppliers</p>,
    show_header: true,
    is_default: false,
    is_sidebar: true,
    icon: "fas fa-user-friends",
  },
  {
    path: "/ports",
    key: localStrings.PORTS_ROUTE_HEADER,
    exact: false,
    is_protected: true,
    component: () => <p>this is ports</p>,
    show_header: true,
    is_default: false,
    is_sidebar: true,
    icon: "fas fa-gifts",
  },
  {
    path: "/role-base-access",
    key: localStrings.ROLE_BASE_ACCESS_ROUTE_HEADER,
    exact: false,
    is_protected: true,
    component: () => <p>this is role base access</p>,
    show_header: true,
    is_default: false,
    is_sidebar: true,
    icon: "fas fa-user-tag",
  },
  {
    path: "/estimated-calculator",
    key: localStrings.ESTIMATED_CALCULATOR_ROUTE_HEADER,
    exact: false,
    is_protected: true,
    component: () => <p>this is estimated calculator</p>,
    show_header: true,
    is_default: false,
    is_sidebar: true,
    icon: "fas fa-calculator",
  },
];

export default ROUTES;
